### PR TITLE
Add ExpandedController to chromecast usage

### PR DESCRIPTION
**Pull request by jakequade**
Love your work, and this incredible library. Great job!

In good faith, I wanted to offer some chromecast functionalities. I noticed it wasn't on the roadmap, I hope this is okay :)

- Implements [ExpandedController](https://react-native-google-cast.github.io/docs/components/ExpandedController) when chromecast play button variant is pressed, allowing for scrubbing of media.
- Patches an issue where pressing the play button while chromecasted content is already playing causes it to restart. Now, it checks against titles and does not restart if the titles are the same.
- Modified the websocket call to consider insecure network paths

Note: extending the androidmanifest.xml was done by way of [this suggested post](https://forums.expo.dev/t/how-to-edit-android-manifest-was-build/65663/4)

Thanks again for this great app, happy to help / change anything as requested. This has been tested on Android using a Samsung Galaxy S21. I'm not able to test on iOS unfortunately, hopefully it plays nicely with the [existing config option](https://github.com/fredrikburmester/streamyfin/blob/a89d9c1f676a1f6645770aecf3bab585fad2dd5d/app.json#L55)

### CODE REVIEW

**Comment by fredrikburmester** [comment]
Amazing! Thank you for this contribution 😁

**Comment by fredrikburmester** [comment]
@jakequade Just to double check, this is for android only right? Is it possible to create a similar plugin for iOS, in a similar way?

**Comment by jakequade** [comment]
@fredrikburmester i'll need to make some ios adjustments on my end in a few hours (ios deployment target differences on my mac). it should work for iOS given the app.json setting for iOS linked above (sorry, on my phone atm). Happy to test it out and confirm once I'm back at keyboard in a couple hours.

**Comment by fredrikburmester** [comment]
The existing app.json implementation is not working as far as i know. I don't think that setting is supported in the expo config. I opened an issue here: https://github.com/react-native-google-cast/react-native-google-cast/issues/538

**Comment by jakequade** [comment]
@fredrikburmester I've pushed a patch that injects the ios appdelegate code [via a mod](https://docs.expo.dev/config-plugins/plugins-and-mods/). I've had intermittent app signing issues when testing (generated xcode project doesn't like that my iphone isn't part of your expo team's signing config), so if you're able to test it that would be awesome. Alternatively I can send you my device guid and I could try running the eas build once you've provisioned it.

**Comment by fredrikburmester** [comment]
You can probably just remove the id from the config and that'll solve the signing issues! Not exactly sure but it worked for another contributor.

**Comment by jakequade** [comment]
@fredrikburmester nice - you're right, not rebuilding the `ios` directory had tripped me up. I've just tested on an iPhone 13 and it works the same as android. Scrubbing works, also has buttons for volume and captions.

**Comment by jakequade** [comment]
IMG_0019

From iPhone. The interface isn't the prettiest, but it's a starting point (I would have thought the background would be populated by the cast lib).

**Comment by fredrikburmester** [comment]
Wow that's a great looking interface! Last time I used the extended controls it did not look that great. Did you create the interface just now?

**Comment by jakequade** [comment]
Nope, it's just the default ExpandedController as far as I'm aware - [source](https://developers.google.com/cast/docs/design_checklist/sender#sender-expanded-controller). :) glad it looks okay

**Comment by jakequade** [comment]
Have had a further test, this needs some changes. Getting intermittent loading issues a couple seconds into casts. Sorry, will fix.

**Comment by MajorP93** [comment]
Looks very promising! Thanks for the contribution!

I am also very much interested in having scrub controls working when streaming to Chromecast.

Any updates on the buffering issues @jakequade ?

**Comment by jakequade** [comment]
@fredrikburmester apologies for the delay, no good excuse. I've found the source of the buffering issues, latest commit removes an additional play function call. This works as expected now, happy for you to have a look if you're able :)  cc @MajorP93

**Comment by fredrikburmester** [comment]
Thank you, no worries at all! Will check it out as soon as possible.

**Comment by jakequade** [comment]
Damn, great work on the metadata changes - it looks so good on the testflight version! Works a charm. Thanks so much for everything. Might have a poke around the needs help issues.

**Comment by fredrikburmester** [comment]
No, thank you! 🔥 the expanded controls are great!

> Might have a poke around the needs help issues.

That would be amazing!

**Comment by fredrikburmester** [comment]
@jakequade This just got released: https://github.com/react-native-google-cast/react-native-google-cast/releases/tag/4.8.3

Should we change our implementation to use this or keep the current one? What do you think?

**Comment by fredrikburmester** [comment]
@jakequade if you want, please join our discord so we can discuss more!

**Pull request merged**
